training:
  num_workers: 10
  batch_size: 10
  exp_name: ''
  epochs: 10
  lr: 0.001
  weight_decay: 0.001 # 0.01 for training from scratch best result
  momentum: 0.9
  lr_scheduler: cosine
  opt: ADAM
  lr_peak_epoch: 2
  label_smoothing: 0.0
  disable_logging: False
  data_root: "/mnt/xfs/projects/proteins/datasets/pdb/pdb_wds"
  only_non_bn_weight_decay: False
  mixed_precision: 1
  self_supervised: 1
  max_seq_len: 1024
  burn_in: 0
logging:
  do_if_complete: False
  mmap_logdir: ""
model:
  arch: "facebook/esm2_t30_150M_UR50D"
  coordinator_hparams: "terminator_configs/coordinator.json"
  gnn_checkpoint: ''
data:
    train_wds_path: "train/shard-{000000..000019}.tar"
    #train_wds_path: "val/{000000..000004}.tar"
    val_wds_path: "val/{000000..000004}.tar"
    sharded: 1
distributed:
  distributed: 0
  world_size: 1
  address: localhost
  dist_train_len: 170000
  dist_val_len: 4200
